SET SQL DIALECT 1;

/* CREATE DATABASE 'commander:/usr/interbase/weaving6.gdb' PAGE_SIZE 4096

 DEFAULT CHARACTER SET  */

/* Table: CLEANJOB, Owner: SYSDBA */

CREATE TABLE CLEANJOB 
(
  SCENARIONO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  GROUPNO	INTEGER,
  PLACENO	INTEGER,
  STARTDATE	TIMESTAMP,
  FINISHDATE	TIMESTAMP,
CONSTRAINT PCLEANJOB PRIMARY KEY (SCENARIONO, JOBNO)
);

/* Table: DOWNTIMEJOB, Owner: SYSDBA */

CREATE TABLE DOWNTIMEJOB 
(
  SCENARIONO	INTEGER NOT NULL,
  LOOMNO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  PLACENO	INTEGER NOT NULL,
  DESCR	CHAR(20) NOT NULL,
  STARTDATE	TIMESTAMP,
  ENDDATE	TIMESTAMP,
CONSTRAINT PDOWNTIMEJOB PRIMARY KEY (SCENARIONO, JOBNO)
);

/* Table: DOWNTIMETYPE, Owner: SYSDBA */

CREATE TABLE DOWNTIMETYPE 
(
  DESCR	CHAR(20) NOT NULL,
  DUMMYINT	INTEGER,
CONSTRAINT PDOWNTIME PRIMARY KEY (DESCR)
);

/* Table: FABRICTYPE, Owner: SYSDBA */

CREATE TABLE FABRICTYPE 
(
  FABRICSTRU	CHAR(3) NOT NULL,
  FABRICCOL	CHAR(3) NOT NULL,
  WARPTYPE	CHAR(2) NOT NULL,
  WARPCOL	CHAR(3) NOT NULL,
  WEFTSTRU	CHAR(4) NOT NULL,
  WEFTTWIST	CHAR(2) NOT NULL,
  WEFTCOL	CHAR(3) NOT NULL,
  PIECELEN	INTEGER NOT NULL,
  WARPPCEWGT	DOUBLE PRECISION,
  WEFTPCEWGT	DOUBLE PRECISION,
  HRSPERPIECE	DOUBLE PRECISION,
CONSTRAINT PFABRICTYPE PRIMARY KEY (FABRICSTRU, FABRICCOL)
);

/* Table: GREIGEOUTPUT, Owner: SYSDBA */

CREATE TABLE GREIGEOUTPUT 
(
  SCHENARIONO	INTEGER NOT NULL,
  READYDATE	TIMESTAMP NOT NULL,
  VBSTRU	CHAR(3) NOT NULL,
  VBCOL	CHAR(3) NOT NULL,
  PIECES	INTEGER NOT NULL,
CONSTRAINT PGRIEGEOUTPUT PRIMARY KEY (READYDATE, VBSTRU, VBCOL)
);

/* Table: LOOMSPEC, Owner: SYSDBA */

CREATE TABLE LOOMSPEC 
(
  REF	CHAR(12) NOT NULL,
  POSN	INTEGER NOT NULL,
  LOOMSPECTYPE	CHAR(25) NOT NULL,
  DESCR	CHAR(25) NOT NULL,
CONSTRAINT PLOOMSPEC PRIMARY KEY (REF)
);

/* Table: PARAMS, Owner: SYSDBA */

CREATE TABLE PARAMS 
(
  SUNHRS	DOUBLE PRECISION NOT NULL,
  MONHRS	DOUBLE PRECISION NOT NULL,
  TUEHRS	DOUBLE PRECISION NOT NULL,
  WEDHRS	DOUBLE PRECISION NOT NULL,
  THUHRS	DOUBLE PRECISION NOT NULL,
  FRIHRS	DOUBLE PRECISION NOT NULL,
  SATHRS	DOUBLE PRECISION NOT NULL,
  REELCHANGEHRS	DOUBLE PRECISION,
  ACTIVESCENARIO	INTEGER,
CONSTRAINT PPARAMS PRIMARY KEY (SUNHRS)
);

/* Table: REEDJOB, Owner: SYSDBA */

CREATE TABLE REEDJOB 
(
  SCENARIONO	INTEGER NOT NULL,
  LOOMNO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  PLACENO	INTEGER NOT NULL,
  TOTALENDS	INTEGER NOT NULL,
  DENTSPERCM	DOUBLE PRECISION NOT NULL,
  STARTDATE	TIMESTAMP,
  ENDDATE	TIMESTAMP,
CONSTRAINT PREEDJOB PRIMARY KEY (SCENARIONO, JOBNO)
);

/* Table: SCENARIO, Owner: SYSDBA */

CREATE TABLE SCENARIO 
(
  SCENARIONO	INTEGER NOT NULL,
  DESCR	CHAR(25),
CONSTRAINT PSCENARIO PRIMARY KEY (SCENARIONO)
);

/* Table: SPINITEM, Owner: SYSDBA */

CREATE TABLE SPINITEM 
(
  SCENARIONO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  ITEMNO	INTEGER NOT NULL,
  GROUPNO	INTEGER,
  PLACENO	INTEGER,
  STRUCT	CHAR(4),
  TWIST	CHAR(2),
  COLOR	CHAR(3),
  WEIGHT	INTEGER,
  HOURSPERKG	DOUBLE PRECISION,
  SPINDLES	INTEGER,
CONSTRAINT PSPINITEM PRIMARY KEY (SCENARIONO, JOBNO, ITEMNO)
);

/* Table: SPINJOB, Owner: SYSDBA */

CREATE TABLE SPINJOB 
(
  SCENARIONO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  GROUPNO	INTEGER,
  PLACENO	INTEGER,
  STARTDATE	TIMESTAMP,
  FINISHDATE	TIMESTAMP,
CONSTRAINT PSPINJOB PRIMARY KEY (SCENARIONO, JOBNO)
);

/* Table: SPINPARAMS, Owner: SYSDBA */

CREATE TABLE SPINPARAMS 
(
  SUNHRS	DOUBLE PRECISION NOT NULL,
  MONHRS	DOUBLE PRECISION NOT NULL,
  TUEHRS	DOUBLE PRECISION NOT NULL,
  WEDHRS	DOUBLE PRECISION NOT NULL,
  THUHRS	DOUBLE PRECISION NOT NULL,
  FRIHRS	DOUBLE PRECISION NOT NULL,
  SATHRS	DOUBLE PRECISION NOT NULL,
  SPINCHANGEHRS	DOUBLE PRECISION,
CONSTRAINT PSPINPARAMS PRIMARY KEY (SUNHRS)
);

/* Table: SPINSCENARIO, Owner: SYSDBA */

CREATE TABLE SPINSCENARIO 
(
  SCENARIONO	INTEGER NOT NULL,
  DESCR	CHAR(25),
CONSTRAINT PSPINSCENARIO PRIMARY KEY (SCENARIONO)
);

/* Table: SPINWORKHOURS, Owner: SYSDBA */

CREATE TABLE SPINWORKHOURS 
(
  WORKDAY	TIMESTAMP NOT NULL,
  GROUP1HRS	DOUBLE PRECISION,
  GROUP2HRS	DOUBLE PRECISION,
  GROUP3HRS	DOUBLE PRECISION,
CONSTRAINT PSPINWORKHOURS PRIMARY KEY (WORKDAY)
);

/* Table: STRULOOM, Owner: SYSDBA */

CREATE TABLE STRULOOM 
(
  FABRICSTRU	CHAR(3) NOT NULL,
  LOOMTYPE	CHAR(25) NOT NULL,
  DUMMYINT	INTEGER,
CONSTRAINT PSTRULOOM PRIMARY KEY (FABRICSTRU, LOOMTYPE)
);

/* Table: WARPTYPE, Owner: SYSDBA */

CREATE TABLE WARPTYPE 
(
  WARPTYPE	CHAR(2) NOT NULL,
  TOTALENDS	INTEGER,
  DENTSPERCM	DOUBLE PRECISION,
  AVEHRS	DOUBLE PRECISION,
  GREIGELENPERCENT	DOUBLE PRECISION,
  WARPLEN	INTEGER,
  WARPWGT	DOUBLE PRECISION,
CONSTRAINT PWARPTYPE PRIMARY KEY (WARPTYPE)
);

/* Table: WEAVEITEM, Owner: SYSDBA */

CREATE TABLE WEAVEITEM 
(
  SCENARIONO	INTEGER NOT NULL,
  SCHEDULENO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  ITEMNO	INTEGER NOT NULL,
  PLACENO	INTEGER NOT NULL,
  FABRICSTRU	CHAR(3) NOT NULL,
  FABRICCOL	CHAR(3) NOT NULL,
  WEFTCOL	CHAR(3) NOT NULL,
  WEFTPCS	INTEGER NOT NULL,
CONSTRAINT PSCENARIOJOBITEM PRIMARY KEY (SCENARIONO, JOBNO, ITEMNO)
);

/* Table: WEAVEJOB, Owner: SYSDBA */

CREATE TABLE WEAVEJOB 
(
  SCENARIONO	INTEGER NOT NULL,
  LOOMNO	INTEGER NOT NULL,
  JOBNO	INTEGER NOT NULL,
  PLACENO	INTEGER NOT NULL,
  WARPTYPE	CHAR(2) NOT NULL,
  WARPCOL	CHAR(3) NOT NULL,
  WARPLEN	INTEGER NOT NULL,
  STARTDATE	TIMESTAMP,
  ENDDATE	TIMESTAMP,
CONSTRAINT PWEAVEJOB PRIMARY KEY (SCENARIONO, JOBNO)
);

/* Table: WORKHOURS, Owner: SYSDBA */

CREATE TABLE WORKHOURS 
(
  WORKDAY	TIMESTAMP NOT NULL,
  LOOM1HRS	DOUBLE PRECISION,
  LOOM2HRS	DOUBLE PRECISION,
  LOOM3HRS	DOUBLE PRECISION,
  LOOM4HRS	DOUBLE PRECISION,
  LOOM5HRS	DOUBLE PRECISION,
  LOOM6HRS	DOUBLE PRECISION,
  LOOM7HRS	DOUBLE PRECISION,
  LOOM8HRS	DOUBLE PRECISION,
  LOOM9HRS	DOUBLE PRECISION,
  LOOM10HRS	DOUBLE PRECISION,
CONSTRAINT PWORKHOURS PRIMARY KEY (WORKDAY)
);
ALTER TABLE DOWNTIMEJOB ADD CONSTRAINT FDOWNTIMEJOBSCENARIONO FOREIGN KEY (SCENARIONO) REFERENCES SCENARIO (SCENARIONO);
ALTER TABLE FABRICTYPE ADD CONSTRAINT FFABRICSTRUWARPTYPE FOREIGN KEY (WARPTYPE) REFERENCES WARPTYPE (WARPTYPE);
ALTER TABLE REEDJOB ADD CONSTRAINT FREEDJOBSCENARIONO FOREIGN KEY (SCENARIONO) REFERENCES SCENARIO (SCENARIONO);
ALTER TABLE WEAVEITEM ADD CONSTRAINT FWEAVEITEM FOREIGN KEY (SCENARIONO, JOBNO) REFERENCES WEAVEJOB (SCENARIONO, JOBNO);
ALTER TABLE WEAVEJOB ADD CONSTRAINT WEAVEJOBSCENARIONO FOREIGN KEY (SCENARIONO) REFERENCES SCENARIO (SCENARIONO);

CREATE GENERATOR GENJOBNO;
CREATE GENERATOR GENSPINJOBNO;
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */

CREATE PROCEDURE SPJOBNO 
RETURNS
(
  CODE INTEGER
)
AS
BEGIN EXIT; END ^

CREATE PROCEDURE SPSPINJOBNO 
RETURNS
(
  CODE INTEGER
)
AS
BEGIN EXIT; END ^


ALTER PROCEDURE SPJOBNO 
RETURNS
(
  CODE INTEGER
)
AS
 
begin
  code=gen_id(genJobNo,1);
end
 ^


ALTER PROCEDURE SPSPINJOBNO 
RETURNS
(
  CODE INTEGER
)
AS
 
begin
  code=gen_id(genspinJobNo,1);
end
 ^

SET TERM ; ^
COMMIT WORK;
SET AUTODDL ON;

/* Grant Roles for this database */


/* Grant permissions for this database */

GRANT SELECT ON CLEANJOB TO BARBARA;
GRANT SELECT ON CLEANJOB TO BARRY;
GRANT SELECT ON CLEANJOB TO BELINDA;
GRANT SELECT ON CLEANJOB TO ESTELLE;
GRANT SELECT ON CLEANJOB TO EUGENE;
GRANT SELECT ON CLEANJOB TO EUGENEA;
GRANT SELECT ON CLEANJOB TO GEORGINA;
GRANT SELECT ON CLEANJOB TO JOANVW;
GRANT SELECT ON CLEANJOB TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON CLEANJOB TO LINDAC;
GRANT SELECT ON CLEANJOB TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON CLEANJOB TO NATALIA;
GRANT SELECT ON CLEANJOB TO PAUL;
GRANT SELECT ON CLEANJOB TO RUTHANE;
GRANT SELECT ON CLEANJOB TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON CLEANJOB TO VIVIAN;
GRANT SELECT ON DOWNTIMEJOB TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DOWNTIMEJOB TO BARRY;
GRANT SELECT ON DOWNTIMEJOB TO BELINDA;
GRANT SELECT ON DOWNTIMEJOB TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DOWNTIMEJOB TO DAVID;
GRANT SELECT ON DOWNTIMEJOB TO ESTELLE;
GRANT SELECT ON DOWNTIMEJOB TO EUGENE;
GRANT SELECT ON DOWNTIMEJOB TO EUGENEA;
GRANT SELECT ON DOWNTIMEJOB TO GEORGINA;
GRANT SELECT ON DOWNTIMEJOB TO GLODENE;
GRANT SELECT ON DOWNTIMEJOB TO JOANVW;
GRANT SELECT ON DOWNTIMEJOB TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOWNTIMEJOB TO LINDAC;
GRANT SELECT ON DOWNTIMEJOB TO MARIO;
GRANT SELECT ON DOWNTIMEJOB TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOWNTIMEJOB TO NATALIA;
GRANT SELECT, REFERENCES ON DOWNTIMEJOB TO PAUL;
GRANT SELECT ON DOWNTIMEJOB TO RUTHANE;
GRANT SELECT ON DOWNTIMEJOB TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOWNTIMEJOB TO VIVIAN;
GRANT SELECT ON DOWNTIMETYPE TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DOWNTIMETYPE TO BARRY;
GRANT SELECT ON DOWNTIMETYPE TO BELINDA;
GRANT SELECT ON DOWNTIMETYPE TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON DOWNTIMETYPE TO DAVID;
GRANT SELECT ON DOWNTIMETYPE TO ESTELLE;
GRANT SELECT ON DOWNTIMETYPE TO EUGENE;
GRANT SELECT ON DOWNTIMETYPE TO EUGENEA;
GRANT SELECT ON DOWNTIMETYPE TO GEORGINA;
GRANT SELECT ON DOWNTIMETYPE TO GLODENE;
GRANT SELECT ON DOWNTIMETYPE TO JOANVW;
GRANT SELECT ON DOWNTIMETYPE TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOWNTIMETYPE TO LINDAC;
GRANT SELECT ON DOWNTIMETYPE TO MARIO;
GRANT SELECT ON DOWNTIMETYPE TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOWNTIMETYPE TO NATALIA;
GRANT SELECT, REFERENCES ON DOWNTIMETYPE TO PAUL;
GRANT SELECT ON DOWNTIMETYPE TO RUTHANE;
GRANT SELECT ON DOWNTIMETYPE TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOWNTIMETYPE TO VIVIAN;
GRANT SELECT ON FABRICTYPE TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON FABRICTYPE TO BARRY;
GRANT SELECT ON FABRICTYPE TO BELINDA;
GRANT SELECT ON FABRICTYPE TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON FABRICTYPE TO DAVID;
GRANT SELECT ON FABRICTYPE TO ESTELLE;
GRANT SELECT ON FABRICTYPE TO EUGENE;
GRANT SELECT ON FABRICTYPE TO EUGENEA;
GRANT SELECT ON FABRICTYPE TO GEORGINA;
GRANT SELECT ON FABRICTYPE TO GLODENE;
GRANT SELECT ON FABRICTYPE TO JOANVW;
GRANT SELECT ON FABRICTYPE TO JUANITA;
GRANT SELECT ON FABRICTYPE TO KEITH;
GRANT DELETE, INSERT, SELECT, UPDATE ON FABRICTYPE TO LINDAC;
GRANT SELECT ON FABRICTYPE TO MARIO;
GRANT SELECT ON FABRICTYPE TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON FABRICTYPE TO NATALIA;
GRANT SELECT, REFERENCES ON FABRICTYPE TO PAUL;
GRANT SELECT ON FABRICTYPE TO RUTHANE;
GRANT SELECT ON FABRICTYPE TO SIDWELL;
GRANT SELECT ON FABRICTYPE TO SUSAN;
GRANT DELETE, INSERT, SELECT, UPDATE ON FABRICTYPE TO VIVIAN;
GRANT SELECT ON GREIGEOUTPUT TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GREIGEOUTPUT TO BARRY;
GRANT SELECT ON GREIGEOUTPUT TO BELINDA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON GREIGEOUTPUT TO DAVID;
GRANT SELECT ON GREIGEOUTPUT TO ESTELLE;
GRANT SELECT ON GREIGEOUTPUT TO EUGENE;
GRANT SELECT ON GREIGEOUTPUT TO EUGENEA;
GRANT SELECT ON GREIGEOUTPUT TO GEORGINA;
GRANT SELECT ON GREIGEOUTPUT TO JOANVW;
GRANT SELECT ON GREIGEOUTPUT TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON GREIGEOUTPUT TO LINDAC;
GRANT SELECT ON GREIGEOUTPUT TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON GREIGEOUTPUT TO NATALIA;
GRANT SELECT, REFERENCES ON GREIGEOUTPUT TO PAUL;
GRANT SELECT ON GREIGEOUTPUT TO RUTHANE;
GRANT SELECT ON GREIGEOUTPUT TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON GREIGEOUTPUT TO VIVIAN;
GRANT SELECT ON LOOMSPEC TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LOOMSPEC TO BARRY;
GRANT SELECT ON LOOMSPEC TO BELINDA;
GRANT SELECT ON LOOMSPEC TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON LOOMSPEC TO DAVID;
GRANT SELECT ON LOOMSPEC TO ESTELLE;
GRANT SELECT ON LOOMSPEC TO EUGENE;
GRANT SELECT ON LOOMSPEC TO EUGENEA;
GRANT SELECT ON LOOMSPEC TO GEORGINA;
GRANT SELECT ON LOOMSPEC TO GLODENE;
GRANT SELECT ON LOOMSPEC TO JOANVW;
GRANT SELECT ON LOOMSPEC TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOOMSPEC TO LINDAC;
GRANT SELECT ON LOOMSPEC TO MARIO;
GRANT SELECT ON LOOMSPEC TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOOMSPEC TO NATALIA;
GRANT SELECT, REFERENCES ON LOOMSPEC TO PAUL;
GRANT SELECT ON LOOMSPEC TO RUTHANE;
GRANT SELECT ON LOOMSPEC TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOOMSPEC TO VIVIAN;
GRANT SELECT ON PARAMS TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PARAMS TO BARRY;
GRANT SELECT ON PARAMS TO BELINDA;
GRANT SELECT ON PARAMS TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON PARAMS TO DAVID;
GRANT SELECT ON PARAMS TO ESTELLE;
GRANT SELECT ON PARAMS TO EUGENE;
GRANT SELECT ON PARAMS TO EUGENEA;
GRANT SELECT ON PARAMS TO GEORGINA;
GRANT SELECT ON PARAMS TO GLODENE;
GRANT SELECT ON PARAMS TO JOANVW;
GRANT SELECT ON PARAMS TO JUANITA;
GRANT SELECT ON PARAMS TO KEITH;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAMS TO LINDAC;
GRANT SELECT ON PARAMS TO MARIO;
GRANT SELECT ON PARAMS TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAMS TO NATALIA;
GRANT SELECT ON PARAMS TO PAUL;
GRANT SELECT ON PARAMS TO RUTHANE;
GRANT SELECT ON PARAMS TO SIDWELL;
GRANT SELECT ON PARAMS TO SUSAN;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAMS TO VIVIAN;
GRANT SELECT ON REEDJOB TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REEDJOB TO BARRY;
GRANT SELECT ON REEDJOB TO BELINDA;
GRANT SELECT ON REEDJOB TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON REEDJOB TO DAVID;
GRANT SELECT ON REEDJOB TO ESTELLE;
GRANT SELECT ON REEDJOB TO EUGENE;
GRANT SELECT ON REEDJOB TO EUGENEA;
GRANT SELECT ON REEDJOB TO GEORGINA;
GRANT SELECT ON REEDJOB TO GLODENE;
GRANT SELECT ON REEDJOB TO JOANVW;
GRANT SELECT ON REEDJOB TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON REEDJOB TO LINDAC;
GRANT SELECT ON REEDJOB TO MARIO;
GRANT SELECT ON REEDJOB TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON REEDJOB TO NATALIA;
GRANT SELECT, REFERENCES ON REEDJOB TO PAUL;
GRANT SELECT ON REEDJOB TO RUTHANE;
GRANT SELECT ON REEDJOB TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON REEDJOB TO VIVIAN;
GRANT SELECT ON SCENARIO TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCENARIO TO BARRY;
GRANT SELECT ON SCENARIO TO BELINDA;
GRANT SELECT ON SCENARIO TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON SCENARIO TO DAVID;
GRANT SELECT ON SCENARIO TO ESTELLE;
GRANT SELECT ON SCENARIO TO EUGENE;
GRANT SELECT ON SCENARIO TO EUGENEA;
GRANT SELECT ON SCENARIO TO GEORGINA;
GRANT SELECT ON SCENARIO TO GLODENE;
GRANT SELECT ON SCENARIO TO JOANVW;
GRANT SELECT ON SCENARIO TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SCENARIO TO LINDAC;
GRANT SELECT ON SCENARIO TO MARIO;
GRANT SELECT ON SCENARIO TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SCENARIO TO NATALIA;
GRANT SELECT, REFERENCES ON SCENARIO TO PAUL;
GRANT SELECT ON SCENARIO TO RUTHANE;
GRANT SELECT ON SCENARIO TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SCENARIO TO VIVIAN;
GRANT SELECT ON SPINITEM TO BARBARA;
GRANT SELECT ON SPINITEM TO BARRY;
GRANT SELECT ON SPINITEM TO BELINDA;
GRANT SELECT ON SPINITEM TO ESTELLE;
GRANT SELECT ON SPINITEM TO EUGENE;
GRANT SELECT ON SPINITEM TO EUGENEA;
GRANT SELECT ON SPINITEM TO GEORGINA;
GRANT SELECT ON SPINITEM TO JOANVW;
GRANT SELECT ON SPINITEM TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINITEM TO LINDAC;
GRANT SELECT ON SPINITEM TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINITEM TO NATALIA;
GRANT SELECT ON SPINITEM TO PAUL;
GRANT SELECT ON SPINITEM TO RUTHANE;
GRANT SELECT ON SPINITEM TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINITEM TO VIVIAN;
GRANT SELECT ON SPINJOB TO BARBARA;
GRANT SELECT ON SPINJOB TO BARRY;
GRANT SELECT ON SPINJOB TO BELINDA;
GRANT SELECT ON SPINJOB TO ESTELLE;
GRANT SELECT ON SPINJOB TO EUGENE;
GRANT SELECT ON SPINJOB TO EUGENEA;
GRANT SELECT ON SPINJOB TO GEORGINA;
GRANT SELECT ON SPINJOB TO JOANVW;
GRANT SELECT ON SPINJOB TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINJOB TO LINDAC;
GRANT SELECT ON SPINJOB TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINJOB TO NATALIA;
GRANT SELECT ON SPINJOB TO PAUL;
GRANT SELECT ON SPINJOB TO RUTHANE;
GRANT SELECT ON SPINJOB TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINJOB TO VIVIAN;
GRANT SELECT ON SPINPARAMS TO BARBARA;
GRANT SELECT ON SPINPARAMS TO BARRY;
GRANT SELECT ON SPINPARAMS TO BELINDA;
GRANT SELECT ON SPINPARAMS TO ESTELLE;
GRANT SELECT ON SPINPARAMS TO EUGENE;
GRANT SELECT ON SPINPARAMS TO EUGENEA;
GRANT SELECT ON SPINPARAMS TO GEORGINA;
GRANT SELECT ON SPINPARAMS TO JOANVW;
GRANT SELECT ON SPINPARAMS TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINPARAMS TO LINDAC;
GRANT SELECT ON SPINPARAMS TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINPARAMS TO NATALIA;
GRANT SELECT ON SPINPARAMS TO PAUL;
GRANT SELECT ON SPINPARAMS TO RUTHANE;
GRANT SELECT ON SPINPARAMS TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINPARAMS TO VIVIAN;
GRANT SELECT ON SPINSCENARIO TO BARBARA;
GRANT SELECT ON SPINSCENARIO TO BARRY;
GRANT SELECT ON SPINSCENARIO TO BELINDA;
GRANT SELECT ON SPINSCENARIO TO ESTELLE;
GRANT SELECT ON SPINSCENARIO TO EUGENE;
GRANT SELECT ON SPINSCENARIO TO EUGENEA;
GRANT SELECT ON SPINSCENARIO TO GEORGINA;
GRANT SELECT ON SPINSCENARIO TO JOANVW;
GRANT SELECT ON SPINSCENARIO TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINSCENARIO TO LINDAC;
GRANT SELECT ON SPINSCENARIO TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINSCENARIO TO NATALIA;
GRANT SELECT ON SPINSCENARIO TO PAUL;
GRANT SELECT ON SPINSCENARIO TO RUTHANE;
GRANT SELECT ON SPINSCENARIO TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINSCENARIO TO VIVIAN;
GRANT SELECT ON SPINWORKHOURS TO BARBARA;
GRANT SELECT ON SPINWORKHOURS TO BARRY;
GRANT SELECT ON SPINWORKHOURS TO BELINDA;
GRANT SELECT ON SPINWORKHOURS TO ESTELLE;
GRANT SELECT ON SPINWORKHOURS TO EUGENE;
GRANT SELECT ON SPINWORKHOURS TO EUGENEA;
GRANT SELECT ON SPINWORKHOURS TO GEORGINA;
GRANT SELECT ON SPINWORKHOURS TO JOANVW;
GRANT SELECT ON SPINWORKHOURS TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINWORKHOURS TO LINDAC;
GRANT SELECT ON SPINWORKHOURS TO MARIO;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINWORKHOURS TO NATALIA;
GRANT SELECT ON SPINWORKHOURS TO PAUL;
GRANT SELECT ON SPINWORKHOURS TO RUTHANE;
GRANT SELECT ON SPINWORKHOURS TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON SPINWORKHOURS TO VIVIAN;
GRANT SELECT ON STRULOOM TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON STRULOOM TO BARRY;
GRANT SELECT ON STRULOOM TO BELINDA;
GRANT SELECT ON STRULOOM TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON STRULOOM TO DAVID;
GRANT SELECT ON STRULOOM TO ESTELLE;
GRANT SELECT ON STRULOOM TO EUGENE;
GRANT SELECT ON STRULOOM TO EUGENEA;
GRANT SELECT ON STRULOOM TO GEORGINA;
GRANT SELECT ON STRULOOM TO GLODENE;
GRANT SELECT ON STRULOOM TO JOANVW;
GRANT SELECT ON STRULOOM TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRULOOM TO LINDAC;
GRANT SELECT ON STRULOOM TO MARIO;
GRANT SELECT ON STRULOOM TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRULOOM TO NATALIA;
GRANT SELECT, REFERENCES ON STRULOOM TO PAUL;
GRANT SELECT ON STRULOOM TO RUTHANE;
GRANT SELECT ON STRULOOM TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRULOOM TO VIVIAN;
GRANT SELECT ON WARPTYPE TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WARPTYPE TO BARRY;
GRANT SELECT ON WARPTYPE TO BELINDA;
GRANT SELECT ON WARPTYPE TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WARPTYPE TO DAVID;
GRANT SELECT ON WARPTYPE TO ESTELLE;
GRANT SELECT ON WARPTYPE TO EUGENE;
GRANT SELECT ON WARPTYPE TO EUGENEA;
GRANT SELECT ON WARPTYPE TO GEORGINA;
GRANT SELECT ON WARPTYPE TO GLODENE;
GRANT SELECT ON WARPTYPE TO JOANVW;
GRANT SELECT ON WARPTYPE TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON WARPTYPE TO LINDAC;
GRANT SELECT ON WARPTYPE TO MARIO;
GRANT SELECT ON WARPTYPE TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON WARPTYPE TO NATALIA;
GRANT SELECT, REFERENCES ON WARPTYPE TO PAUL;
GRANT SELECT ON WARPTYPE TO RUTHANE;
GRANT SELECT ON WARPTYPE TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON WARPTYPE TO VIVIAN;
GRANT SELECT ON WEAVEITEM TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WEAVEITEM TO BARRY;
GRANT SELECT ON WEAVEITEM TO BELINDA;
GRANT SELECT ON WEAVEITEM TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WEAVEITEM TO DAVID;
GRANT SELECT ON WEAVEITEM TO ESTELLE;
GRANT SELECT ON WEAVEITEM TO EUGENE;
GRANT SELECT ON WEAVEITEM TO EUGENEA;
GRANT SELECT ON WEAVEITEM TO GEORGINA;
GRANT SELECT ON WEAVEITEM TO GLODENE;
GRANT SELECT ON WEAVEITEM TO JOANVW;
GRANT SELECT ON WEAVEITEM TO JUANITA;
GRANT SELECT ON WEAVEITEM TO KEITH;
GRANT DELETE, INSERT, SELECT, UPDATE ON WEAVEITEM TO LINDAC;
GRANT SELECT ON WEAVEITEM TO MARIO;
GRANT SELECT ON WEAVEITEM TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON WEAVEITEM TO NATALIA;
GRANT SELECT, REFERENCES ON WEAVEITEM TO PAUL;
GRANT SELECT ON WEAVEITEM TO RUTHANE;
GRANT SELECT ON WEAVEITEM TO SIDWELL;
GRANT SELECT ON WEAVEITEM TO SUSAN;
GRANT DELETE, INSERT, SELECT, UPDATE ON WEAVEITEM TO VIVIAN;
GRANT SELECT ON WEAVEJOB TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WEAVEJOB TO BARRY;
GRANT SELECT ON WEAVEJOB TO BELINDA;
GRANT SELECT ON WEAVEJOB TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WEAVEJOB TO DAVID;
GRANT SELECT ON WEAVEJOB TO ESTELLE;
GRANT SELECT ON WEAVEJOB TO EUGENE;
GRANT SELECT ON WEAVEJOB TO EUGENEA;
GRANT SELECT ON WEAVEJOB TO GEORGINA;
GRANT SELECT ON WEAVEJOB TO GLODENE;
GRANT SELECT ON WEAVEJOB TO JOANVW;
GRANT SELECT ON WEAVEJOB TO JUANITA;
GRANT SELECT ON WEAVEJOB TO KEITH;
GRANT DELETE, INSERT, SELECT, UPDATE ON WEAVEJOB TO LINDAC;
GRANT SELECT ON WEAVEJOB TO MARIO;
GRANT SELECT ON WEAVEJOB TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON WEAVEJOB TO NATALIA;
GRANT SELECT, REFERENCES ON WEAVEJOB TO PAUL;
GRANT SELECT ON WEAVEJOB TO RUTHANE;
GRANT SELECT ON WEAVEJOB TO SIDWELL;
GRANT SELECT ON WEAVEJOB TO SUSAN;
GRANT DELETE, INSERT, SELECT, UPDATE ON WEAVEJOB TO VIVIAN;
GRANT SELECT ON WORKHOURS TO BARBARA;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WORKHOURS TO BARRY;
GRANT SELECT ON WORKHOURS TO BELINDA;
GRANT SELECT ON WORKHOURS TO CORDENAI;
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON WORKHOURS TO DAVID;
GRANT SELECT ON WORKHOURS TO ESTELLE;
GRANT SELECT ON WORKHOURS TO EUGENE;
GRANT SELECT ON WORKHOURS TO EUGENEA;
GRANT SELECT ON WORKHOURS TO GEORGINA;
GRANT SELECT ON WORKHOURS TO GLODENE;
GRANT SELECT ON WORKHOURS TO JOANVW;
GRANT SELECT ON WORKHOURS TO JUANITA;
GRANT DELETE, INSERT, SELECT, UPDATE ON WORKHOURS TO LINDAC;
GRANT SELECT ON WORKHOURS TO MARIO;
GRANT SELECT ON WORKHOURS TO NADIA;
GRANT DELETE, INSERT, SELECT, UPDATE ON WORKHOURS TO NATALIA;
GRANT SELECT ON WORKHOURS TO PAUL;
GRANT SELECT ON WORKHOURS TO RUTHANE;
GRANT SELECT ON WORKHOURS TO SIDWELL;
GRANT DELETE, INSERT, SELECT, UPDATE ON WORKHOURS TO VIVIAN;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO BARBARA;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO BARRY;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO BELINDA;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO DAVID;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO ESTELLE;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO EUGENE;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO EUGENEA;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO GEORGINA;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO JOANVW;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO JUANITA;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO LINDAC;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO MARIO;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO NATALIA;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO PAUL;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO PUBLIC;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO RUTHANE;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO SIDWELL;
GRANT EXECUTE ON PROCEDURE SPJOBNO TO VIVIAN;
GRANT EXECUTE ON PROCEDURE SPSPINJOBNO TO LINDAC;
GRANT EXECUTE ON PROCEDURE SPSPINJOBNO TO NATALIA;
GRANT EXECUTE ON PROCEDURE SPSPINJOBNO TO PUBLIC;
GRANT EXECUTE ON PROCEDURE SPSPINJOBNO TO VIVIAN;
